#include <arch/instruction.h>
#include <stddef.h>

#define REGISTER_INSTRUCTION(w, x, y, z) extern void execute##w##Instruction(Addressing_mode); \
                                      Instruction w##y##instruction = {.name = x, .execute_instruction = &execute##w##Instruction, .opcode = y, .mode = z}; \
                                      instruction_set[y] = w##y##instruction;

Instruction instruction_set[0x100];

void setup_instructions(){
    for(uint16_t i = 0; i < 0x100; i++){
        REGISTER_INSTRUCTION(BRK, "BRK", i, IMPLIED);
    }

    REGISTER_INSTRUCTION(BRK, "BRK", BRK_IMPL, IMPLIED);
    REGISTER_INSTRUCTION(BPL, "BPL", BPL_REL, RELATIVE);
    REGISTER_INSTRUCTION(JSR, "JSR", JSR_ABS, ABSOLUTE);
    REGISTER_INSTRUCTION(BMI, "BMI", BMI_REL, RELATIVE);
    REGISTER_INSTRUCTION(RTI, "RTI", RTI_IMPL, IMPLIED);
    REGISTER_INSTRUCTION(BVC, "BVC", BVC_REL, RELATIVE);
    REGISTER_INSTRUCTION(RTS, "RTS", RTS_IMPL, IMPLIED);
    REGISTER_INSTRUCTION(BVS, "BVS", BVS_REL, RELATIVE);
    REGISTER_INSTRUCTION(BCC, "BCC", BCC_REL, RELATIVE);
    REGISTER_INSTRUCTION(LDY, "LDY", LDY_IMM, IMMEDIATE);
    REGISTER_INSTRUCTION(BCS, "BCS", BCS_REL, RELATIVE);
    REGISTER_INSTRUCTION(CPY, "CPY", CPY_IMM, IMMEDIATE);
    REGISTER_INSTRUCTION(BNE, "BNE", BNE_REL, RELATIVE);
    REGISTER_INSTRUCTION(CPX, "CPX", CPX_IMM, IMMEDIATE);
    REGISTER_INSTRUCTION(BEQ, "BEQ", BEQ_REL, RELATIVE);

    REGISTER_INSTRUCTION(ORA, "ORA", ORA_IND_X, X_INDEXED);
    REGISTER_INSTRUCTION(ORA, "ORA", ORA_IND_Y, Y_INDEXED);
    REGISTER_INSTRUCTION(AND, "AND", AND_IND_X, X_INDEXED);
    REGISTER_INSTRUCTION(AND, "AND", AND_IND_Y, Y_INDEXED);
    REGISTER_INSTRUCTION(EOR, "EOR", EOR_IND_X, X_INDEXED);
    REGISTER_INSTRUCTION(EOR, "EOR", EOR_IND_Y, Y_INDEXED);
    REGISTER_INSTRUCTION(ADC, "ADC", ADC_IND_X, X_INDEXED);
    REGISTER_INSTRUCTION(ADC, "ADC", ADC_IND_Y, Y_INDEXED);
    REGISTER_INSTRUCTION(STA, "STA", STA_IND_X, X_INDEXED);
    REGISTER_INSTRUCTION(STA, "STA", STA_IND_Y, Y_INDEXED);
    REGISTER_INSTRUCTION(LDA, "LDA", LDA_IND_X, X_INDEXED);
    REGISTER_INSTRUCTION(LDA, "LDA", LDA_IND_Y, Y_INDEXED);
    REGISTER_INSTRUCTION(CMP, "CMP", CMP_IND_X, X_INDEXED);
    REGISTER_INSTRUCTION(CMP, "CMP", CMP_IND_Y, Y_INDEXED);
    REGISTER_INSTRUCTION(SBC, "SBC", SBC_IND_X, X_INDEXED);
    REGISTER_INSTRUCTION(SBC, "SBC", SBC_IND_Y, Y_INDEXED);
    
    REGISTER_INSTRUCTION(LDX, "LDX", LDX_IMM, IMMEDIATE);
    
    REGISTER_INSTRUCTION(LDA, "LDA", LDA_IMM, IMMEDIATE);

}